"use client"

import { useState } from "react"
import Link from "next/link"
import {
  FileText,
  Plus,
  Download,
  Filter,
  ChevronDown,
  CheckCircle2,
  Clock,
  Ban,
  Eye,
  ArrowUpRight,
  Receipt,
  ScrollText,
  Pencil,
} from "lucide-react"
import { CRMSidebar } from "@/components/crm/crm-sidebar"
import { CRMTopbar } from "@/components/crm/crm-topbar"
import { useInvoices } from "@/components/crm/invoice-context"
import type { InvoiceRecord, InvoiceStatus, InvoiceType } from "@/data/invoice-types"

const statusConfig: Record<InvoiceStatus, { label: string; color: string; bg: string; icon: typeof CheckCircle2 }> = {
  draft: { label: "Draft", color: "text-gray-600", bg: "bg-gray-100", icon: Pencil },
  sent: { label: "Sent", color: "text-blue-600", bg: "bg-blue-100", icon: ArrowUpRight },
  partially_received: { label: "Partially Received", color: "text-amber-600", bg: "bg-amber-100", icon: Clock },
  balance_received: { label: "Balance Received", color: "text-green-600", bg: "bg-green-100", icon: CheckCircle2 },
  closed: { label: "Closed", color: "text-gray-500", bg: "bg-gray-100", icon: Ban },
}

const typeConfig: Record<InvoiceType, { label: string; color: string; bg: string; icon: typeof FileText }> = {
  invoice: { label: "Invoice", color: "text-[#7060B8]", bg: "bg-[#F0EDF6]", icon: FileText },
  receipt: { label: "Receipt", color: "text-green-600", bg: "bg-green-50", icon: Receipt },
  quotation: { label: "Quotation", color: "text-amber-600", bg: "bg-amber-50", icon: ScrollText },
}

const allStatuses: InvoiceStatus[] = ["draft", "sent", "partially_received", "balance_received", "closed"]

export default function InvoicesPage() {
  const { invoices, updateStatus } = useInvoices()
  const [filterType, setFilterType] = useState<InvoiceType | "all">("all")
  const [filterStatus, setFilterStatus] = useState<InvoiceStatus | "all">("all")
  const [showStatusDropdown, setShowStatusDropdown] = useState<string | null>(null)

  const filtered = invoices.filter((inv) => {
    if (filterType !== "all" && inv.type !== filterType) return false
    if (filterStatus !== "all" && inv.status !== filterStatus) return false
    return true
  })

  function handleUpdateStatus(id: string, newStatus: InvoiceStatus) {
    updateStatus(id, newStatus)
    setShowStatusDropdown(null)
  }

  function downloadPdf(inv: InvoiceRecord) {
    const typeLabel = inv.type === "invoice" ? "INVOICE" : inv.type === "receipt" ? "RECEIPT" : "QUOTATION"
    const lines: string[] = []
    lines.push(typeLabel)
    lines.push("========================================")
    lines.push("")
    lines.push(`Number: ${inv.number}`)
    lines.push(`Date: ${inv.date}`)
    lines.push(`Due: ${inv.dueDate}`)
    lines.push(`Status: ${statusConfig[inv.status].label}`)
    lines.push("")
    lines.push("FROM:")
    lines.push(inv.companyName)
    lines.push("")
    lines.push("TO:")
    lines.push(inv.clientName)
    lines.push(inv.clientAddress)
    lines.push(inv.clientEmail)
    lines.push("")
    lines.push("----------------------------------------")
    lines.push("ITEMS")
    lines.push("----------------------------------------")
    inv.items.forEach((item, i) => {
      lines.push(`${i + 1}. ${item.description}`)
      lines.push(`   Qty: ${item.quantity} x $${item.unitPrice.toLocaleString()} = $${item.amount.toLocaleString()}`)
    })
    lines.push("")
    lines.push(`Subtotal:  $${inv.subtotal.toLocaleString()}`)
    if (inv.taxRate > 0) lines.push(`Tax (${inv.taxRate}%):  $${inv.taxAmount.toLocaleString()}`)
    lines.push(`TOTAL:     $${inv.total.toLocaleString()}`)
    if (inv.paymentType === "partial" && inv.amountPaid) {
      lines.push("")
      lines.push(`Payment Type: Partial`)
      lines.push(`Amount Paid:  $${inv.amountPaid.toLocaleString()}`)
      lines.push(`Balance Due:  $${(inv.total - inv.amountPaid).toLocaleString()}`)
    }
    if (inv.paymentType === "full" && inv.amountPaid) {
      lines.push("")
      lines.push(`Payment Type: Full`)
      lines.push(`Amount Paid:  $${inv.amountPaid.toLocaleString()}`)
      lines.push(`Balance Due:  $0`)
    }
    if (inv.relatedInvoiceId) {
      lines.push("")
      lines.push(`Related: ${inv.relatedInvoiceId}`)
    }
    if (inv.notes) {
      lines.push("")
      lines.push("NOTES:")
      lines.push(inv.notes)
    }
    lines.push("")
    lines.push("========================================")
    lines.push("Generated by HelpTribe CRM")

    const blob = new Blob([lines.join("\n")], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${inv.number}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="bg-[#C4CBDE] h-screen overflow-hidden">
      <div className="h-full max-w-[1400px] mx-auto py-4 px-4">
        <div className="h-full bg-white rounded-[36px] p-5 shadow-elevated">
          <div className="flex gap-5 h-full">
            <CRMSidebar activeItem="invoices" />

            <div className="flex-1 flex flex-col gap-4 overflow-y-auto min-w-0 pr-1">
              <CRMTopbar title="Invoices" subtitle="Manage invoices, receipts, and quotations" />

              {/* Create buttons */}
              <div className="flex gap-3 px-6">
                <Link
                  href="/invoices/new?type=invoice"
                  className="flex items-center gap-2 rounded-xl bg-[#7060B8] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#504098] transition-colors"
                >
                  <Plus className="size-4" />
                  New Invoice
                </Link>
                <Link
                  href="/invoices/new?type=receipt"
                  className="flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-green-700 transition-colors"
                >
                  <Receipt className="size-4" />
                  New Receipt
                </Link>
                <Link
                  href="/invoices/new?type=quotation"
                  className="flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-amber-600 transition-colors"
                >
                  <ScrollText className="size-4" />
                  New Quotation
                </Link>
              </div>

              {/* Filters */}
              <div className="flex items-center gap-3 px-6 flex-wrap">
                <Filter className="size-4 text-[#7B7592]" />
                <div className="flex gap-2">
                  {(["all", "invoice", "receipt", "quotation"] as const).map((t) => (
                    <button
                      key={t}
                      onClick={() => setFilterType(t)}
                      className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                        filterType === t
                          ? "bg-[#7060B8] text-white"
                          : "bg-[#F0EDF6] text-[#4D4764] hover:bg-[#E9E7F0]"
                      }`}
                    >
                      {t === "all" ? "All" : typeConfig[t].label}
                    </button>
                  ))}
                </div>
                <div className="w-px h-5 bg-[#E9E7F0]" />
                <div className="flex gap-2">
                  {(["all", "draft", "sent", "partially_received", "balance_received", "closed"] as const).map((s) => (
                    <button
                      key={s}
                      onClick={() => setFilterStatus(s)}
                      className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${
                        filterStatus === s
                          ? "bg-[#7060B8] text-white"
                          : "bg-[#F0EDF6] text-[#4D4764] hover:bg-[#E9E7F0]"
                      }`}
                    >
                      {s === "all" ? "All Status" : statusConfig[s].label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Table */}
              <div className="px-6 pb-4">
                <div className="rounded-[20px] border border-[#E9E7F0] overflow-hidden">
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="bg-[#F7F7F8] border-b border-[#E9E7F0]">
                        <th className="text-left py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Number</th>
                        <th className="text-left py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Type</th>
                        <th className="text-left py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Client</th>
                        <th className="text-left py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Date</th>
                        <th className="text-right py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Amount</th>
                        <th className="text-left py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Status</th>
                        <th className="text-right py-3 px-4 font-poppins font-semibold text-xs text-[#4D4764]">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      {filtered.map((inv) => {
                        const tc = typeConfig[inv.type]
                        const sc = statusConfig[inv.status]
                        const TypeIcon = tc.icon
                        const StatusIcon = sc.icon
                        return (
                          <tr key={inv.id} className="border-b border-[#E9E7F0] last:border-0 hover:bg-[#F7F7F8] transition-colors">
                            <td className="py-3 px-4 font-medium text-[#28243D]">{inv.number}</td>
                            <td className="py-3 px-4">
                              <span className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-medium ${tc.bg} ${tc.color}`}>
                                <TypeIcon className="size-3" />
                                {tc.label}
                              </span>
                            </td>
                            <td className="py-3 px-4 text-[#4D4764]">{inv.clientName}</td>
                            <td className="py-3 px-4 text-[#4D4764]">{inv.date}</td>
                            <td className="py-3 px-4 text-right font-medium text-[#28243D]">${inv.total.toLocaleString()}</td>
                            <td className="py-3 px-4">
                              <div className="relative">
                                <button
                                  onClick={() => setShowStatusDropdown(showStatusDropdown === inv.id ? null : inv.id)}
                                  className={`inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1 text-xs font-medium ${sc.bg} ${sc.color} hover:opacity-80 transition-opacity cursor-pointer`}
                                >
                                  <StatusIcon className="size-3" />
                                  {sc.label}
                                  <ChevronDown className="size-3" />
                                </button>
                                {showStatusDropdown === inv.id && (
                                  <div className="absolute z-20 top-full left-0 mt-1 bg-white rounded-xl shadow-elevated border border-[#E9E7F0] py-1 min-w-[180px]">
                                    {allStatuses.map((s) => (
                                      <button
                                        key={s}
                                        onClick={() => handleUpdateStatus(inv.id, s)}
                                        className={`w-full text-left px-3 py-2 text-xs hover:bg-[#F0EDF6] flex items-center gap-2 transition-colors ${
                                          inv.status === s ? "font-semibold text-[#7060B8]" : "text-[#4D4764]"
                                        }`}
                                      >
                                        <span className={`size-2 rounded-full ${statusConfig[s].bg} ${statusConfig[s].color}`} style={{ backgroundColor: s === inv.status ? "#7060B8" : undefined }} />
                                        {statusConfig[s].label}
                                      </button>
                                    ))}
                                  </div>
                                )}
                              </div>
                            </td>
                            <td className="py-3 px-4">
                              <div className="flex items-center justify-end gap-2">
                                <Link
                                  href={`/invoices/${inv.id}`}
                                  className="rounded-lg p-1.5 text-[#7060B8] hover:bg-[#F0EDF6] transition-colors"
                                  title="View"
                                >
                                  <Eye className="size-4" />
                                </Link>
                                <button
                                  onClick={() => downloadPdf(inv)}
                                  className="rounded-lg p-1.5 text-[#7060B8] hover:bg-[#F0EDF6] transition-colors"
                                  title="Download PDF"
                                >
                                  <Download className="size-4" />
                                </button>
                              </div>
                            </td>
                          </tr>
                        )
                      })}
                      {filtered.length === 0 && (
                        <tr>
                          <td colSpan={7} className="py-12 text-center text-[#7B7592]">
                            No records found matching your filters.
                          </td>
                        </tr>
                      )}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
